### ISSUE TITLE
Users question

### ISSUE THREAD

**Issue by mikysal78** [jethrocarr/namedmanager#47] opened 2017-02-26 22:06 UTC
users: michele, pippo, pluto etc...
michele access to only zone michele.tld
pippo access to only zone pippo.tld
etc...
How can it be done?

thanks.
Best regards.
Michele

**Comment by jethrocarr** [comment] 2017-02-27 11:05
Duplicate of #23 - answer is that it is not a supported feature currently.

Pull requests welcome :-)

**Closed by jethrocarr** 2017-02-27 11:05 UTC
